# Setup
title:               Won's blog
tagline:             'Hello World!'
description:         'hello <a href="https://jekyllrb.com" target="_blank">Won's blog</a> page <a href="https://twitter.com/won" target="_blank">@won</a> contact me.'
url:                 'https://myjungjw.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Won
  url:               https://twitter.com/won
  email:             iamwon88@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
