# Setup
title:               'Won's blog'
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@won</a>.'
url:                 'http://myjungjw.github.io'
baseurl:             '/myjungjw'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Won
  url:               https://twitter.com/won
  email:             iamwon88@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
